# Generated by Django 4.1.2 on 2022-11-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='codigo_libro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='codigo_sector',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='codigo_socio',
            field=models.IntegerField(null=True),
        ),
    ]
